### ISSUE TITLE
The screen does not work for the v3.3plus hardware

### ISSUE THREAD

**Issue by zacharyps** [01Space/open-smartwatch-light-3.3plus#1]
# What is not working?
The screen does not work. The pins described in include/osw_pins.h do not match the hardware of the osw-light-3.3plus that is sold on banggood. This whole repository is just an outdated copy of the original open-smartwatch-os. The manufacturer of this version of the hardware based it on the similarly named version of that project. However, the display is not connected to the same IO pins of the on-board esp32-pico-d4. The display back light will turn on but the screen never displays anything. Everything else seems to run fine. Debug messages over serial connection show that the rest of the software is working nominally.

# How to reproduce this
1. Purchase this product (https://usa.banggood.com/Open-Smartwatch-Light-V3_3plus-ESP32-Programming-Watch-Development-Board-p-1914006.html)
2. Flash the software from this repository or the original repository Open-Smartwatch/open-smartwatch-light.
3. Press the reset button to boot up the watch
4. The screen back light will be on but the screen will never display anything.

# What should happen instead?
The screen is supposed to turn on and show the time.

# Environment
- open-smartwatch-light-3.3plus
- This issue is not limited to this or the original osw operating system. I have successfully run simple test code on the 3.3plus board. The screen still does not work while using the TFT values shown below. It also does not work with the pin values of the gps editions.
#define TFT_CS ~~5~~
#define TFT_DC ~~12~~
#define TFT_RST ~~33~~
#define TFT_SCK ~~18~~
#define TFT_MOSI ~~23~~
#define TFT_MISO ~~-1~~  // no data coming back
#define TFT_LED ~~9~~

# Additional context
To the creator of this repository or the manufacturer - please release the correct display pins. They are defined incorrectly in the file include/osw_pins.h
If anyone else knows the pin values please let me know so I can fix this.

**Comment by 01Space** [comment]
#define TFT_CS 5
#define TFT_DC 12
#define TFT_RST 33
#define TFT_SCK 18
#define TFT_MOSI 23
#define TFT_MISO -1 // no data coming back
#define TFT_LED 9
This pin definition is correct

Please select when compiling
LIGHT_EDITION_V3_3

**Comment by zacharyps** [comment]
Sorry, it turns out that the screen pins were not soldered onto the board fully. When I tested the pins it looked connected but was not. Thanks for your help anyway.
